SEQ_6 = [0, 1, 2, 3, 4, 5]

MOVE_ANIM_MANIFEST = {
    "fork_flick": {
        "motion": "jab",
        "projectile_path": "none",
        "projectile_delay": 0.0,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 0.0,
        "body_size": 112,
        "effect_size": 74,
        "projectile_size": 0,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "sauce_splash": {
        "motion": "whip",
        "projectile_path": "sauce_arc",
        "projectile_delay": 0.20,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 12.0,
        "body_size": 118,
        "effect_size": 82,
        "projectile_size": 78,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "al_dente_slam": {
        "motion": "slam",
        "projectile_path": "none",
        "projectile_delay": 0.0,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 0.0,
        "body_size": 118,
        "effect_size": 86,
        "projectile_size": 0,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "meatball_panic": {
        "motion": "toss",
        "projectile_path": "meatball",
        "projectile_delay": 0.16,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 12.0,
        "body_size": 116,
        "effect_size": 86,
        "projectile_size": 76,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "drum_knock": {
        "motion": "drum_hit",
        "projectile_path": "none",
        "projectile_delay": 0.0,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 0.0,
        "body_size": 110,
        "effect_size": 72,
        "projectile_size": 0,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "sahur_burst": {
        "motion": "beat",
        "projectile_path": "sound_ring",
        "projectile_delay": 0.10,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 12.0,
        "body_size": 110,
        "effect_size": 82,
        "projectile_size": 74,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "tung_roll": {
        "motion": "roll",
        "projectile_path": "drum_spin",
        "projectile_delay": 0.18,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 12.0,
        "body_size": 112,
        "effect_size": 86,
        "projectile_size": 78,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "midnight_march": {
        "motion": "march",
        "projectile_path": "step_wave",
        "projectile_delay": 0.16,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 12.0,
        "body_size": 110,
        "effect_size": 84,
        "projectile_size": 78,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "pirouette_pour": {
        "motion": "spin",
        "projectile_path": "coffee_arc",
        "projectile_delay": 0.20,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 12.0,
        "body_size": 106,
        "effect_size": 82,
        "projectile_size": 76,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "foam_ribbon": {
        "motion": "ribbon",
        "projectile_path": "foam_ribbon",
        "projectile_delay": 0.18,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 12.0,
        "body_size": 106,
        "effect_size": 82,
        "projectile_size": 80,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "arabesque_roast": {
        "motion": "arabesque",
        "projectile_path": "roast_arc",
        "projectile_delay": 0.20,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 12.0,
        "body_size": 108,
        "effect_size": 84,
        "projectile_size": 78,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "finale_froth": {
        "motion": "finale",
        "projectile_path": "froth_bloom",
        "projectile_delay": 0.14,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 12.0,
        "body_size": 108,
        "effect_size": 86,
        "projectile_size": 78,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "sneaker_snap": {
        "motion": "jab",
        "projectile_path": "none",
        "projectile_delay": 0.0,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 0.0,
        "body_size": 112,
        "effect_size": 76,
        "projectile_size": 0,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "tralala_wave": {
        "motion": "beat",
        "projectile_path": "sound_ring",
        "projectile_delay": 0.12,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 12.0,
        "body_size": 114,
        "effect_size": 82,
        "projectile_size": 76,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "reef_rush": {
        "motion": "roll",
        "projectile_path": "none",
        "projectile_delay": 0.0,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 0.0,
        "body_size": 116,
        "effect_size": 84,
        "projectile_size": 0,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "coral_chorus": {
        "motion": "finale",
        "projectile_path": "froth_bloom",
        "projectile_delay": 0.16,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 12.0,
        "body_size": 116,
        "effect_size": 86,
        "projectile_size": 80,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "silent_sip": {
        "motion": "jab",
        "projectile_path": "none",
        "projectile_delay": 0.0,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 0.0,
        "body_size": 110,
        "effect_size": 74,
        "projectile_size": 0,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "crema_dagger": {
        "motion": "toss",
        "projectile_path": "roast_arc",
        "projectile_delay": 0.14,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 12.0,
        "body_size": 110,
        "effect_size": 82,
        "projectile_size": 76,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "shadow_roast": {
        "motion": "arabesque",
        "projectile_path": "none",
        "projectile_delay": 0.0,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 0.0,
        "body_size": 112,
        "effect_size": 84,
        "projectile_size": 0,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "espresso_exit": {
        "motion": "spin",
        "projectile_path": "coffee_arc",
        "projectile_delay": 0.18,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 12.0,
        "body_size": 112,
        "effect_size": 82,
        "projectile_size": 76,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "orbit_kick": {
        "motion": "roll",
        "projectile_path": "none",
        "projectile_delay": 0.0,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 0.0,
        "body_size": 118,
        "effect_size": 82,
        "projectile_size": 0,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "milky_way_moo": {
        "motion": "beat",
        "projectile_path": "sound_ring",
        "projectile_delay": 0.12,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 12.0,
        "body_size": 118,
        "effect_size": 86,
        "projectile_size": 80,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "ring_charge": {
        "motion": "roll",
        "projectile_path": "drum_spin",
        "projectile_delay": 0.16,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 12.0,
        "body_size": 118,
        "effect_size": 86,
        "projectile_size": 80,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "nova_hoof": {
        "motion": "slam",
        "projectile_path": "none",
        "projectile_delay": 0.0,
        "body_fps": 12.0,
        "effect_fps": 12.0,
        "projectile_fps": 0.0,
        "body_size": 120,
        "effect_size": 88,
        "projectile_size": 0,
        "body_seq": SEQ_6,
        "effect_seq": SEQ_6,
        "projectile_seq": SEQ_6,
    },
    "runway_rush": {"motion": "roll", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 116, "effect_size": 82, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "bomb_burst": {"motion": "toss", "projectile_path": "meatball", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 116, "effect_size": 86, "projectile_size": 78, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "croco_cannon": {"motion": "beat", "projectile_path": "drum_spin", "projectile_delay": 0.18, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 118, "effect_size": 86, "projectile_size": 80, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "tail_rotor": {"motion": "march", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 118, "effect_size": 84, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "cooler_kick": {"motion": "jab", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 116, "effect_size": 76, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "frost_spit": {"motion": "toss", "projectile_path": "foam_ribbon", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 116, "effect_size": 82, "projectile_size": 78, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "ice_box_crash": {"motion": "slam", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 118, "effect_size": 88, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "desert_chill": {"motion": "beat", "projectile_path": "sound_ring", "projectile_delay": 0.14, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 118, "effect_size": 84, "projectile_size": 80, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "branch_bonk": {"motion": "drum_hit", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 112, "effect_size": 74, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "pinecone_pop": {"motion": "toss", "projectile_path": "meatball", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 112, "effect_size": 80, "projectile_size": 72, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "brrr_blast": {"motion": "beat", "projectile_path": "sound_ring", "projectile_delay": 0.14, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 112, "effect_size": 84, "projectile_size": 78, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "mossy_mayhem": {"motion": "slam", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 114, "effect_size": 86, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "peel_jab": {"motion": "jab", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 108, "effect_size": 74, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "banana_boomerang": {"motion": "toss", "projectile_path": "coffee_arc", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 110, "effect_size": 80, "projectile_size": 76, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "monkey_mash": {"motion": "roll", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 112, "effect_size": 84, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "bananini_barrage": {"motion": "finale", "projectile_path": "froth_bloom", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 112, "effect_size": 86, "projectile_size": 78, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "scurry_slice": {"motion": "jab", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 108, "effect_size": 74, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "crust_comet": {"motion": "toss", "projectile_path": "sauce_arc", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 108, "effect_size": 80, "projectile_size": 76, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "mozza_mob": {"motion": "beat", "projectile_path": "sound_ring", "projectile_delay": 0.12, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 110, "effect_size": 84, "projectile_size": 76, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "oven_ambush": {"motion": "slam", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 112, "effect_size": 86, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "layer_lash": {"motion": "whip", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 116, "effect_size": 80, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "ricotta_rattle": {"motion": "toss", "projectile_path": "foam_ribbon", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 116, "effect_size": 82, "projectile_size": 78, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "coil_crush": {"motion": "roll", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 118, "effect_size": 84, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "bake_coil": {"motion": "finale", "projectile_path": "roast_arc", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 118, "effect_size": 86, "projectile_size": 78, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "scoop_smack": {"motion": "jab", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 112, "effect_size": 74, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "frost_swirl": {"motion": "spin", "projectile_path": "foam_ribbon", "projectile_delay": 0.18, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 112, "effect_size": 82, "projectile_size": 78, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "sundae_slide": {"motion": "roll", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 114, "effect_size": 84, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "brain_freeze": {"motion": "beat", "projectile_path": "sound_ring", "projectile_delay": 0.12, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 114, "effect_size": 84, "projectile_size": 78, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "kernel_kick": {"motion": "jab", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 118, "effect_size": 76, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "corn_quake": {"motion": "slam", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 120, "effect_size": 88, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "golden_roar": {"motion": "beat", "projectile_path": "sound_ring", "projectile_delay": 0.12, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 118, "effect_size": 84, "projectile_size": 80, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "polenta_meteor": {"motion": "toss", "projectile_path": "meatball", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 120, "effect_size": 86, "projectile_size": 80, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "string_sting": {"motion": "ribbon", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 112, "effect_size": 80, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "ganache_glint": {"motion": "toss", "projectile_path": "coffee_arc", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 112, "effect_size": 80, "projectile_size": 76, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "puppet_pivot": {"motion": "spin", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 112, "effect_size": 82, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "marzipan_mirage": {"motion": "finale", "projectile_path": "froth_bloom", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 114, "effect_size": 86, "projectile_size": 78, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "crown_crimp": {"motion": "jab", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 114, "effect_size": 76, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "sauce_decree": {"motion": "toss", "projectile_path": "sauce_arc", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 114, "effect_size": 82, "projectile_size": 76, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "noble_fold": {"motion": "roll", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 116, "effect_size": 84, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "ravioli_reign": {"motion": "finale", "projectile_path": "froth_bloom", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 116, "effect_size": 86, "projectile_size": 78, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "link_lash": {"motion": "whip", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 114, "effect_size": 80, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "pepper_spear": {"motion": "toss", "projectile_path": "roast_arc", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 114, "effect_size": 82, "projectile_size": 76, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "grill_grind": {"motion": "roll", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 116, "effect_size": 84, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "coliseum_sear": {"motion": "beat", "projectile_path": "sound_ring", "projectile_delay": 0.12, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 116, "effect_size": 84, "projectile_size": 78, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "crust_cudgel": {"motion": "jab", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 114, "effect_size": 76, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "olive_order": {"motion": "toss", "projectile_path": "meatball", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 114, "effect_size": 80, "projectile_size": 74, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "toast_takedown": {"motion": "slam", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 116, "effect_size": 86, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "boss_banquet": {"motion": "finale", "projectile_path": "froth_bloom", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 116, "effect_size": 86, "projectile_size": 78, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "toast_tread": {"motion": "roll", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 118, "effect_size": 84, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "tomato_mortar": {"motion": "toss", "projectile_path": "sauce_arc", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 118, "effect_size": 82, "projectile_size": 78, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "garlic_guard": {"motion": "drum_hit", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 116, "effect_size": 76, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "bruschetta_barrage": {"motion": "beat", "projectile_path": "sound_ring", "projectile_delay": 0.12, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 118, "effect_size": 84, "projectile_size": 80, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "curd_claw": {"motion": "jab", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 114, "effect_size": 76, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "stretch_beam": {"motion": "ribbon", "projectile_path": "foam_ribbon", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 114, "effect_size": 82, "projectile_size": 78, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "pride_pounce": {"motion": "roll", "projectile_path": "none", "projectile_delay": 0.0, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 0.0, "body_size": 116, "effect_size": 84, "projectile_size": 0, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
    "melt_majesty": {"motion": "finale", "projectile_path": "froth_bloom", "projectile_delay": 0.16, "body_fps": 12.0, "effect_fps": 12.0, "projectile_fps": 12.0, "body_size": 116, "effect_size": 86, "projectile_size": 78, "body_seq": SEQ_6, "effect_seq": SEQ_6, "projectile_seq": SEQ_6},
}
